---
- name: Check if Pi-hole is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/pihole"
  register: pihole_binary

- name: Set fact about Pi-hole is installed or not
  ansible.builtin.set_fact:
    pihole_installed: "{{ pihole_binary.stat.exists }}"

- name: Create Pi-Hole configuration directory
  ansible.builtin.file:
    name: "{{ pihole_path_config }}"
    state: directory
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0755

- name: Setup initial and needed configuration for unattended upgrade
  ansible.builtin.template:
    src: "setupVars.conf.j2"
    dest: "{{ pihole_path_config }}/setupVars.conf"
    owner: root
    group: root
    mode: 0644

- name: download install script
  ansible.builtin.get_url:
    url: https://install.pi-hole.net
    dest: ~/basic-install.sh
    mode: u+rwx
  when: not pihole_installed

- name: Run install script
  ansible.builtin.command:
    cmd: "~/basic-install.sh --unattended"
  when: not pihole_installed
